dubbo:
    application:
        name: dubbo-consumer
        register-mode: instance
        metadata-type: local
        qos-enable: false
        logger: slf4j
    config-center:
        address: nacos://150.158.15.11:38848
        username: nacos
        password: 123456
        namespace: dev
        group: dubbo
    registry:
        address: nacos://150.158.15.11:38848
        username: nacos
        password: 123456
        parameters:
            namespace: dev
        group: dubbo
        cluster: default
    metadata-report:
        address: nacos://150.158.15.11:38848
        username: nacos
        password: 123456
        parameters:
            namespace: dev
        group: dubbo
    protocol:
      heartbeat: 36000000
    reference:
        org.apache.dubbo.springboot.demo.DemoService.sayHello.timeout: 41000
        org.apache.dubbo.springboot.demo.DemoService.timeout: 31000
